name: plwiki-builder
executables:
  build:
    source-dirs: .
    main: Main.hs
    language: GHC2021
    default-extensions:
      - LambdaCase
    ghc-options: -Wall -O3 -rtsopts -threaded -with-rtsopts=-IO
    dependencies:
      - base
      - filepath
      - directory
      - bytestring
      - text
      - data-default
      - blaze-html
      - shakespeare
      - aeson
      - yaml
      - pandoc-types
      - pandoc
      - shake
      - transformers
      - mtl
      - network-uri
